In [123]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [124]:
df = pd.read_csv("token_usage.csv")

In [125]:
df["task_id"] = df["task_id"].replace("20250215-120903", "survery Large Language Model papers")

In [126]:
df

,prompt_tokens,completion_tokens,cached_tokens,task_id,model
0,170620,443,0,0,gpt-4o-mini
1,1444,142,0,0,gpt-4o-2024-11-20
2,2966,111,0,0,gpt-4o-2024-11-20
3,494798,1354,0,0,gpt-4o-mini
4,5449,54,0,0,gpt-4o-2024-11-20
...,...,...,...,...,...
892,167756,404,0,14,gpt-4o-mini
893,4003,119,0,14,gpt-4o-2024-11-20
894,2113,160,0,14,gpt-4o-2024-11-20
895,2765,221,0,14,gpt-4o-2024-11-20
896,2310,408,0,14,gpt-4o-2024-11-20

In [127]:
s = df.groupby(by=["task_id","model"]).sum()

In [128]:
type(s)

pandas.core.frame.DataFrame

In [129]:
s= s.reset_index(drop=False)

In [130]:
s

,task_id,model,prompt_tokens,completion_tokens,cached_tokens
0,0,gpt-4o-2024-11-20,96997,3861,0
1,0,gpt-4o-mini,1467332,3726,0
2,1,gpt-4o-2024-11-20,93184,3769,0
3,1,gpt-4o-mini,1620890,4414,0
4,2,gpt-4o-2024-11-20,116290,4386,0
5,2,gpt-4o-mini,1655014,4395,0
6,3,gpt-4o-2024-11-20,113111,5235,0
7,3,gpt-4o-mini,1347898,3449,0
8,4,gpt-4o-2024-11-20,143915,4937,0
9,4,gpt-4o-mini,2303370,6208,0
10,5,gpt-4o-2024-11-20,99464,3538,0
11,5,gpt-4o-mini,1740324,4638,0
12,6,gpt-4o-2024-11-20,120941,4656,0
13,6,gpt-4o-mini,1919475,5048,0
14,7,gpt-4o-2024-11-20,147322,8425,0
15,7,gpt-4o-mini,1686213,4034,0
16,8,gpt-4o-2024-11-20,59136,4388,0
17,8,gpt-4o-mini,855903,2120,0
18,9,gpt-4o-2024-11-20,72211,3137,0
19,9,gpt-4o-mini,1484394,3560,0
20,10,gpt-4o-2024-11-20,76915,3365,0
21,10,gpt-4o-mini,1254057,3041,0
22,11,gpt-4o-2024-11-20,301910,12381,0
23,11,gpt-4o-mini,5843735,15197,0
24,12,gpt-4o-2024-11-20,352998,16061,0
25,12,gpt-4o-mini,5630460,14771,0
26,13,gpt-4o-2024-11-20,161286,6163,0
27,13,gpt-4o-mini,3017110,7634,0
28,14,gpt-4o-2024-11-20,157462,6539,0
29,14,gpt-4o-mini,2380088,6110,0

In [131]:
def cost_function(row):
    if (row["model"] == "gpt-4o-mini"):
        return row["prompt_tokens"]* 0.15/1000000.0 + 0.6 /1000000.0 * row["completion_tokens"]
    else:
        return row["prompt_tokens"]* 2.5/1000000.0 + 10.0 /1000000.0 * row["completion_tokens"]

In [132]:
s["cost"] = s.apply(cost_function, axis= 1)

In [133]:
s

,task_id,model,prompt_tokens,completion_tokens,cached_tokens,cost
0,0,gpt-4o-2024-11-20,96997,3861,0,0.281103
1,0,gpt-4o-mini,1467332,3726,0,0.222335
2,1,gpt-4o-2024-11-20,93184,3769,0,0.270650
3,1,gpt-4o-mini,1620890,4414,0,0.245782
4,2,gpt-4o-2024-11-20,116290,4386,0,0.334585
5,2,gpt-4o-mini,1655014,4395,0,0.250889
6,3,gpt-4o-2024-11-20,113111,5235,0,0.335128
7,3,gpt-4o-mini,1347898,3449,0,0.204254
8,4,gpt-4o-2024-11-20,143915,4937,0,0.409158
9,4,gpt-4o-mini,2303370,6208,0,0.349230
10,5,gpt-4o-2024-11-20,99464,3538,0,0.284040
11,5,gpt-4o-mini,1740324,4638,0,0.263831
12,6,gpt-4o-2024-11-20,120941,4656,0,0.348913
13,6,gpt-4o-mini,1919475,5048,0,0.290950
14,7,gpt-4o-2024-11-20,147322,8425,0,0.452555
15,7,gpt-4o-mini,1686213,4034,0,0.255352
16,8,gpt-4o-2024-11-20,59136,4388,0,0.191720
17,8,gpt-4o-mini,855903,2120,0,0.129657
18,9,gpt-4o-2024-11-20,72211,3137,0,0.211898
19,9,gpt-4o-mini,1484394,3560,0,0.224795
20,10,gpt-4o-2024-11-20,76915,3365,0,0.225938
21,10,gpt-4o-mini,1254057,3041,0,0.189933
22,11,gpt-4o-2024-11-20,301910,12381,0,0.878585
23,11,gpt-4o-mini,5843735,15197,0,0.885678
24,12,gpt-4o-2024-11-20,352998,16061,0,1.043105
25,12,gpt-4o-mini,5630460,14771,0,0.853432
26,13,gpt-4o-2024-11-20,161286,6163,0,0.464845
27,13,gpt-4o-mini,3017110,7634,0,0.457147
28,14,gpt-4o-2024-11-20,157462,6539,0,0.459045
29,14,gpt-4o-mini,2380088,6110,0,0.360679

In [134]:
s["cost"].sum()

np.float64(11.375211450000002)

In [135]:
s2 = s.loc[[2,3,6,7,10,11,12,13,14,15,16,17]]

In [136]:
s2 = s2.copy().reset_index(drop=True)

In [137]:
s2.to_csv("testreport.csv")